version: '3'

services:
  web:
    build:
      context: .  # Utiliza el contexto actual (donde se encuentra el Dockerfile)
      dockerfile: Dockerfile  # Utiliza el Dockerfile que hemos definido
    ports:
      - "8080:80"  # Mapea el puerto 8080 del host al puerto 80 del contenedor
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: checador
      MYSQL_USER: victor
      MYSQL_PASSWORD: pass123 
      TZ: America/Mexico_City

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9090:80"  # Mapea el puerto 9090 del host al puerto 80 del contenedor
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: example_root_password
